[alias]
panel-macos = "run --features gpu --bin panel"
panel-app-macos = "run --features gpu --bin macos_bundle -- panel build"
open-panel-app-macos = "run --features gpu --bin macos_bundle -- panel open"
install-panel-app-macos = "run --features gpu --bin macos_bundle -- panel install"
install-open-panel-app-macos = "run --features gpu --bin macos_bundle -- panel install-open"
ime-app-macos = "run --features gpu --bin macos_bundle -- ime build"
open-ime-app-macos = "run --features gpu --bin macos_bundle -- ime open"
install-ime-app-macos = "run --features gpu --bin macos_bundle -- ime install"
install-open-ime-app-macos = "run --features gpu --bin macos_bundle -- ime install-open"
enable-ime-app-macos = "run --features gpu --bin macos_bundle -- ime enable"
install-enable-ime-app-macos = "run --features gpu --bin macos_bundle -- ime install-enable"
test-gpu = "test --features gpu"
ime-host = "run --features gpu --bin ime_host"
android-ime-host = "run --features gpu --bin android_ime_host"
android-doctor = "run --features gpu --bin android_doctor"
