[alias]
panel-macos = "run --features gpu --bin panel"
panel-app-macos = "run --features gpu --bin macos_bundle -- panel build"
open-panel-app-macos = "run --features gpu --bin macos_bundle -- panel open"
install-panel-app-macos = "run --features gpu --bin macos_bundle -- panel install"
install-open-panel-app-macos = "run --features gpu --bin macos_bundle -- panel install-open"
ime-app-macos = "run --features gpu --bin macos_bundle -- ime build"
open-ime-app-macos = "run --features gpu --bin macos_bundle -- ime open"
install-ime-app-macos = "run --features gpu --bin macos_bundle -- ime install"
install-open-ime-app-macos = "run --features gpu --bin macos_bundle -- ime install-open"
test-gpu = "test --features gpu"
